/*
 * generated by Xtext 2.11.0
 */
package de.wwu.musket.ide

import com.google.inject.Guice
import de.wwu.musket.MusketRuntimeModule
import de.wwu.musket.MusketStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MusketIdeSetup extends MusketStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MusketRuntimeModule, new MusketIdeModule))
	}
	
}
